// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuaHangHung.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230522033838_Create_Table_Kho")]
    partial class Create_Table_Kho
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("CuaHangHung.Models.HoaDon", b =>
                {
                    b.Property<string>("HoaDonCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoaDonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SanPhamCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoLuong")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HoaDonCode");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("CuaHangHung.Models.KhachHang", b =>
                {
                    b.Property<string>("KhachHangCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KhachHangName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KhachHangCode");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("CuaHangHung.Models.Kho", b =>
                {
                    b.Property<string>("KhoID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportKho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryKho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KhoStoreExists")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberbKho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SanPhamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KhoID");

                    b.ToTable("Khoss");
                });

            modelBuilder.Entity("CuaHangHung.Models.NhanVien", b =>
                {
                    b.Property<string>("NhanVienCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NhanVienName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NhanVienCode");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("CuaHangHung.Models.SanPham", b =>
                {
                    b.Property<string>("SanPhamCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SanPhamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SanPhamCode");

                    b.ToTable("SanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
